title: AWS re/Start Portfolio
description: A portfolio documenting hands-on AWS labs and projects from the AWS re/Start Program
author: Nhlanhla Malaza
url: https://omoinjm.github.io/aws-restart-portfolio
baseurl: "/aws-restart-portfolio"
